name: alpha-lfm

dependencies:
  - python=3.8.8
  - pip
  - pip:
    - tensorflow-1.15.4+nv-cp38-cp38-win_amd64.whl
    - easydict==1.9
    - protobuf==3.20.3
    - scipy==1.6.2
    - scikit-image==0.18.1
    - numpy==1.18.3
    - matplotlib==3.4.1
    - mat73==0.59